<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\User;

class UserController extends Controller{
    private $public_page=[
        '/',
        'site/login'
    ];

    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action){
        $cookie=Yii::$app->request->cookies;
        $page_path=trim(Yii::$app->request->pathInfo);

        if($cookie->has('owl_admin_uid')&&$cookie->has('owl_admin_key')&&$cookie->has('owl_admin_token')){
            $user_id=$cookie->get('owl_admin_uid','');
            $mask_code=$cookie->get('owl_admin_key','');
            $hash=$cookie->get('owl_admin_token','');

            if($user_id===''||$mask_code===''||$hash===''){
                $this->redirect('/');
            }else{
                $class_user=new User;
                $re=$class_user->check_login($user_id,$mask_code,$hash);

                if($re===false){
                    $this->redirect('/');
                }else{
                    if($page_path===''){
                        $this->redirect('/media/input-list');
                    }
//                    $this->user_id=$user_id;
//                    $this->user_name=$user;
                }
            }
        }else{
            if($page_path!==''&&!in_array($page_path,$this->public_page)){
                $this->redirect('/');
            }
        }
        return true;
    }



//    public function beforeAction($action){
//        $cookie=Yii::$app->request->cookies;
//        $page_path=trim(Yii::$app->request->pathInfo);
//
//        if($cookie->has('owl_uid')&&$cookie->has('owl_key')&&$cookie->has('owl_token')) {
//            $user_id=$cookie->get('owl_uid','');
//            $mask_code=$cookie->get('owl_key','');
//            $hash=$cookie->get('owl_token','');
//
//            if($user_id===''||$mask_code===''||$hash===''){
//                $this->redirect('/');
//            }else{
//                $class_user=new User;
//                $user=$class_user->check_login($user_id,$mask_code,$hash);
//                if($user===false){
////                    $this->redirect('/');
//                }else{
//                    if($page_path===''){
//                        $this->redirect('/site/mode');
//                    }
//                    $this->user_id=$user_id;
//                    $this->user_name=$user;
//                }
//            }
//        }else{
//            if($page_path!==''&&!in_array($page_path,$this->public_page)){
//                $this->redirect('/');
//            }
//        }
//        return true;
//    }
}
